### ISSUE TITLE
multicolor in RMarkdown?

### ISSUE THREAD

**Issue by aedobbyn** [aedobbyn/multicolor#1]
Thanks to @cortinah for the suggestion!

**Comment by cortinah** [comment]
Looks like `fansi` package might be a way to implement:
https://cran.rstudio.com/web/packages/fansi/vignettes/sgr-in-rmd.html

will read up on this.

**Comment by cortinah** [comment]
Yay! I got multicolor to work in .Rmd files.  At least for single-line output.   And I think I know how to get it to work on multi-line output, but this will require a new type in multi_color().  Check this out:

---
title: "Multicolor Rmd Test"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(crayon.enabled=TRUE)
library(multicolor)
library(fansi)
```

## `r sgr_to_html(multi_color('R Markdown', type='string'))`

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r testmc, comment=NA, results="asis", echo=FALSE}
sgr_to_html(multi_color('Hello, World  ', type='string'))
cat('\n\n')

sgr_to_html(
multi_color("taste the rainbow",
            c("mediumpurple",
              "rainbow",
             "cyan3"), type='string')
             )
```

**Comment by aedobbyn** [comment]
Ah nice! It's not working for me but maybe this is a super quick fix.

![screen shot 2018-12-20 at 4 30 37 pm](https://user-images.githubusercontent.com/4908283/50311878-a99f0800-0474-11e9-820e-2d7bb6cc9a15.jpg)

I put the code for the rmd (adapted from above) [in my dev branch](https://github.com/aedobbyn/multicolor/blob/dev/test_rmd.Rmd). Is your code somewhere?

**Comment by cortinah** [comment]
Please try the knitting the file in this gist:
https://gist.github.com/cortinah/4b6397310a14b425ddde7d3f0080c8eb

This should work... thanks!  This is just a test to see how to make it work.  Some changes that we should probably do:

1) don't display the logo in rmarkdown
2) add a "rmd" type that takes care of everything

Happy holidays!

**Comment by aedobbyn** [comment]
Nice!! That worked. Very cool!

Agreed on 1. For 2, do you mean add a new `type` in addition to message, warning, and string and then the user would specify that `type` is `rmd` whenever using `multicolor` in an RMarkdown document?

**Comment by aedobbyn** [comment]
@cortinah this is on the master branch now. If you get a chance let me know what you think!

**Comment by cortinah** [comment]
Hi @aedobbyn , hope you are well!  thank you for all the work.  I installed and tested it. This is great.

My thoughts:
1) the !inside_knitr() .onAttach is great!  I didn't think it was possible to detect that multicolor was being loaded inside rmarkdown to prevent logo display.  nice find. really.
2) The new "rmd" type seems to be working great (with one small exception) see below.
3) The addition of a vignette for rmd usage is exactly what I was thinking about as well!

Small question:  the package title in DESCRIPTION currently is: "Add Multiple Colors to your Console Output".   Should we consider updating it to "Add Multiple Colors to your Console & RMarkdown Output" ?    This would reflect the package's new capability.
----
Minor issue with type='rmd' functionality:

I can't quite figure out why there are quotation marks around the html output text such as the Brutus text on the vignette, which outputs like:

[1] “Brutus... 

 ... but not in the output of inline code such as:

`r multi_color("Header Output",  colors = wesanderson::wes_palettes$Darjeeling1, type = "rmd")`
which doesn't come out with the quotes.

I think ideally we would avoid the quotes in both cases, to mimic the console output.  what do you think?  Thanks again, version 0.12 is looking like a nice update.  Please let me know if I can help with the quotes thing.  I will keep looking. Otherwise looks good to go. All best.

**Comment by cortinah** [comment]
Ha Ha. I fixed the quote issue. Please change line 294 of multi_color.R to:

rmd <- noquote(out) %>% fansi::sgr_to_html()

that does it! :-)

**Comment by cortinah** [comment]
Hi @aedobbyn I did some further testing of the new "rmd" type and found that using it with cowsay doesn't work.  For example, this line in rmarkdown   `multi_color(things$cow, type='rmd')` returns all of its output in a single line. Something with line breaks isn't working.  This would affect all multi-line input, not only cowsay. It may have to do with the fact that you need two spaces at the end of a line in rmarkdown to force a line break.  Not sure if the solution might be to replace \n with two spaces in 'rmd' mode.  That's my guess.

**Comment by aedobbyn** [comment]
Great point. Hmm.

It looks like we need to replace them with `<br>`s but the spacing doesn't work I think because spaces aren't registering? Not sure.

```
multi_color(things$cow, type='rmd', colors = c("blue", "black")) %>% 
  stringr::str_replace_all("<span>\n</span>", "<br>")
```

![Screen Shot 2019-03-21 at 11 38 14 AM](https://user-images.githubusercontent.com/4908283/54764283-da0a5580-4bcd-11e9-9dbf-4c57f69e902e.jpg)

**Comment by cortinah** [comment]
Got it! yay!  This works: (and doesn't seem to mess up anything else)

`multi_color(things$cat,type='rmd')  %>% stringr:::str_replace_all('  '," &nbsp; ") %>% stringr::str_replace_all('\n',"<br>")`

**note: the double space in the first str_replace_all is super important!**

**Comment by aedobbyn** [comment]
Nice!!! 🎉 

I think all we need to do is add a `<br>` at the beginning. I wonder if there's a way to display output in monospace font too, since the animals are a bit off otherwise... 🤔

**Comment by cortinah** [comment]
Hi @aedobbyn, to display the output in monospace, the following changes to the .rmd file are needed:

In the yaml, add:

`output:  
    html_document:  
      css: style.css`

I can't get this to display properly on this box, but you need a new line after output: and a tab before html_document and also css: on its own line with two tabs before it.

Then create a text file called style.css, with this content:

body{
  font-family: Monaco;
  font-size: 16pt;
}
 
This looks like it helps a little.  we are going deep down the rabbit hole at this point..

**Comment by aedobbyn** [comment]
Nice, great point. In later versions of RMarkdown you can use CSS chunks directly like 

```{css}
body {
font-family: Monaco;
font-size: 16pt;
}
```

so that works the same way. This seems like something we can put in the vignette so that people can display cowsay animals correctly, if they want to.

Here's [`an update`](https://github.com/aedobbyn/multicolor/compare/dev?expand=1#diff-66008b874b62442e0a963d51521666dbR295) that solves the issue. What do you think?

**Comment by cortinah** [comment]
I merged and tested the patch and it works fine. Vignette also looks good with the css. thank you. I'll send you my suggestions for the updated README by Monday.

**Comment by aedobbyn** [comment]
Awesome!

So instead of changing the font-family of the entire `body` to a monospace font I was thinking about ways to apply the CSS to only the output of a chunk with `cowsay` content in it. We should I think be able to [apply a CSS class to a chunk](https://github.com/aedobbyn/multicolor/commit/104381c1afb88bd57e17903f0a816be44cea923f#diff-d27148fc34067385146c8268d0e46cc6R17) but that doesn't seem to work when adding the `class = 'cowsay'` or `class.output = 'cowsay'` to the chunk options.

I wrote a [small function](https://github.com/aedobbyn/multicolor/commit/104381c1afb88bd57e17903f0a816be44cea923f#diff-d27148fc34067385146c8268d0e46cc6R33) that would apply a different font family to the text but for some reason it makes the `span` tags in the animal visible. 

The best hack right now seems to be something like

```
<div style='font-family: Monaco;'>

```{r, results='asis'}
multi_color(things$cat, type="rmd", add_leading_newline = TRUE)
```

</div>
```

which is slightly annoying for the user but doesn't show the `span` tags.

**Comment by aedobbyn** [comment]
Oof actually this doesn't work for some animals, like `things$buffalo` 😬 

![Screen Shot 2019-03-24 at 7 15 51 PM](https://user-images.githubusercontent.com/4908283/54887422-45bc1f00-4e69-11e9-8438-35639b6b7e80.jpg)

**Comment by cortinah** [comment]
The issue with the buffalo are the four backticks on its head (hair).  since the backtick has a special meaning in RMD it is messing it up.  The solution would seem to be to replace the backtick with a \` to display a literal backtick.  However, that doesn't seem to be working. I'm going to play around with it.  It might be that that needs to be done first in the pipeline.

**Comment by cortinah** [comment]
I MAY have fixed it once and for all with this:
if (type == "rmd") {
    out <- out %>%
      stringr::str_replace_all("\u0020", "&nbsp;") %>%
      stringr::str_replace_all("\n", "<br>") %>%
      stringr::str_replace_all("\`", "\u2018")

![Screen Shot 2019-03-25 at 10 45 58 AM](https://user-images.githubusercontent.com/22863380/54929014-45646800-4eeb-11e9-8a7d-44debb145c13.png)

**Comment by cortinah** [comment]
This is equivalent and also works (using unicodes):

` if (type == "rmd") {
    out <- out %>%
      stringr::str_replace_all("\u0020", "&nbsp;") %>%
      stringr::str_replace_all("\n", "<br>") %>%
      stringr::str_replace_all("\u0060", "\u2018")
`

**Comment by aedobbyn** [comment]
Okay cool!! The color doesn't seem to be evenly distributed on the buffalo..not sure why 🤔

**Comment by aedobbyn** [comment]
Yeah I think some of the leading color tags aren't being applied to certain characters, even with your suggestion in place in https://github.com/aedobbyn/multicolor/commit/a19286f502df34730b50d65728ed81351d2cb5f1#diff-66008b874b62442e0a963d51521666dbR301, which solves most cases

![Screen Shot 2019-03-28 at 2 40 10 PM](https://user-images.githubusercontent.com/4908283/55184045-941e3600-5167-11e9-9d30-3b0737768d52.jpg)

**Comment by aedobbyn** [comment]
I think it has something to do with underscores since all the uncolored bits happen directly after an underscore

**Comment by cortinah** [comment]
My hack solution is to replace underscores with a slightly different kind of underscore by adding yet another replacement: %>%   stringr::str_replace_all("_", "\u0332")
https://unicode-search.net/unicode-namesearch.pl?term=UNDERSCORE

**Comment by aedobbyn** [comment]
Nice that seems to have fixed it!! Can we think of any other characters that might similarly need replacing?

**Comment by aedobbyn** [comment]
And we should still think of a way to address the CSS issue rather than placing `div`s around outputs that are meant to be monospace hmmm 🤔

**Comment by cortinah** [comment]
i think knitr hooks might be the way. i'll take a look.

**Comment by cortinah** [comment]
I think i got the knitr hook working!  Would you happen to know the name of the default font to return to, after outputting a chunk in Monaco?  i.e what should be the font after our monospace multicolor chunk executes?

**Comment by aedobbyn** [comment]
Hmm good question -- maybe Arial?

**Comment by cortinah** [comment]
So.. the code hook works to make a chunk run in Monaco, but I am having a hard time getting it to go back to "normal".

This is RMD setup chunk:
```
```{r setup, include=FALSE}
library(multicolor)

options(crayon.enabled=TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_hooks$set(
  
  mc_rmd = function(before, options, envir) {
    if (before) {
       return(paste("<div style='font-family: Monaco;'>"))
    } else {
       return(paste("<div style='font-family: Arial; font-size: 16pt;'>"))
    }
} )
```

and then, on the chunk we want to change:
```
```{r mc,results='asis', mc_rmd=TRUE}
multi_color(things$hypnotoad, type='rmd', add_leading_newline = T)
```

However, subsequent chunks in the RMD don't look "normal".  Changing the font back to Arial isn't working as it should

**Comment by aedobbyn** [comment]
Does it need ending `</div>`s maybe?

**Comment by cortinah** [comment]
Thanks!  the below seems to work much better.   let's test it with a few cases. 

```
```{r setup, include=FALSE}
library(multicolor)

options(crayon.enabled=TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_hooks$set(
  
  mc_rmd = function(before, options, envir) {
    if (before) {
       return(paste("<div style='font-family: Monaco;'>"))
    } else {
       return(paste("</div>"))
    }
} )
```

**Comment by aedobbyn** [comment]
Wooo! The last thing I've been trying to do is remove the `[1]` before the output. `cat` won't work for us because it displays the `span` tags.

Some leads here (love the '90s theme for April Fools 😆) but I haven't gotten that knitr hook to work https://stackoverflow.com/questions/22524822/how-can-i-remove-the-prefix-index-indicator-1-in-knitr-output

**Comment by aedobbyn** [comment]
Maybe [`pander`](http://rapporter.github.io/pander/) is the answer
https://stackoverflow.com/questions/15599948/replacing-the-print-function-in-knitr-chunk-evaluation/15600673#15600673

**Comment by cortinah** [comment]
I completely get the aesthetic reasons to remove the [1].  that said, it seems to be a lot of work to remove those three characters, which R users are used to.  in addition, with the add_leading_newline option it's not in the way of the cowsay creature.   So, i support trying to get rid of it, but wouldn't want to make using multicolor more complicated for regular users. hope this makes sense.

**Comment by aedobbyn** [comment]
I think that makes sense. I'll open an issue for the future

**Comment by cortinah** [comment]
thank you -- good idea to open an issue for that.  i like all the improvements we've made!

**Comment by aedobbyn** [comment]
I agree! Any other changes you think we need to make before we're ready to release a new version?

**Comment by cortinah** [comment]
I think we are good -- feel free to add some color selections to the randomized logo on startup? :-)

**Comment by aedobbyn** [comment]
Oh yeah that reminds me about https://github.com/aedobbyn/multicolor/issues/10#issuecomment-477726045. I don't want to step on your toes artistically so I'll leave it up to you to make the change that works with a light background 😄 . Closing this since I think we're good on RMarkdown 🎉
