### ISSUE TITLE
Variety of different logos on startup

### ISSUE THREAD

**Issue by aedobbyn** [aedobbyn/multicolor#10]
I imagine we'd randomize the one that is actually displayed. Could either be a random combination of colors that all look decent together or fully formed logos that are randomized.

Should make sure that these look decent on both dark and light themes (sidenote -- is there a way to detect background color of the console/terminal??)

**Comment by aedobbyn** [comment]
I think the first color in `magma` might be too light on a white background ☹️  BUT I do love them! That's the only issue I can see.

![Screen Shot 2019-03-28 at 2 48 51 PM](https://user-images.githubusercontent.com/4908283/55184583-e875e580-5168-11e9-80ec-5130bc058c4d.jpg)

**Comment by cortinah** [comment]
thanks -- good call -- i can tweak it

**Comment by aedobbyn** [comment]
Btw I moved the logo palettes [here](https://github.com/aedobbyn/multicolor/blob/92b3860b112d2c27373b0e1e055739b6de1ab0b9/R/utils.R#L177) so we can also address #9

**Comment by cortinah** [comment]
Please take a look at this pr: https://github.com/aedobbyn/multicolor/pull/18#issue-267189987

**Comment by aedobbyn** [comment]
Love ghibli! Last color in lacroix might be too light, what do you think

![Screen Shot 2019-04-03 at 5 36 12 PM](https://user-images.githubusercontent.com/4908283/55514858-2b3b3000-5637-11e9-90e6-884cbc4d4259.jpg)

**Comment by cortinah** [comment]
that's right -- Could you please try:

lacroix = c("#EF7C12", "#F4B95A", "#009F3F", "#8FDA04", "#AF6125", "#F4E3C7", "#B25D91", "#EFC7E6", "#EF7C12", "#F4B95A")

I think magma is ok...

**Comment by aedobbyn** [comment]
Nice, I think those are all good!!

**Comment by cortinah** [comment]
ok, i will update and pr
