### ISSUE TITLE
failure in multicolor tests via cowsay revdep check

### ISSUE THREAD

**Issue by sckott** [aedobbyn/multicolor#23]
submitting a new version of `cowsay` - on revdep checks, noticed that multicolor is failing. see https://github.com/sckott/cowsay/blob/master/revdep/problems.md#multicolor

**Comment by aedobbyn** [comment]
fixed in https://github.com/aedobbyn/multicolor/commit/aa06b70a0501aed22ca7d2b1a873639da733a0cf 👍
